//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecetteProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients_Recette
    {
        public int NumRec { get; set; }
        public int NumIng { get; set; }
        public int QteUtilise { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Recette Recette { get; set; }
    }
}
