//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecetteProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recette
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recette()
        {
            this.Ingredients_Recette = new HashSet<Ingredients_Recette>();
        }
    
        public int NumRecette { get; set; }
        public string NomRec { get; set; }
        public System.DateTime DateCreationRec { get; set; }
        public string Difficulte { get; set; }
        public int TempsPreparation { get; set; }
        public string MethodePreparation { get; set; }
        public string Photo { get; set; }
        public int CodeTheme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredients_Recette> Ingredients_Recette { get; set; }
        public virtual Theme Theme { get; set; }
    }
}
